version: "3.7"

services:
  homer:
    image: b4bz/homer:latest
    env_file:
      - stack.env
    ports:
      - 8083:8080
    volumes:
      - /home/pi/config/homer/assets:/www/assets
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # I don't have NFS and I want to edit the config folder
        # so I will run it on a specific node
        constraints: [node.hostname == rpi3b-cluster-2]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homer.rule=Host(`homer.pi-cluster.local`)"
        - "traefik.http.routers.homer.entrypoints=web"
        - "traefik.http.services.homer.loadbalancer.server.port=8080"
        - "traefik.http.routers.homer.service=homer"

networks:
  public:
    external: true
