version: "3.4"

services:
  vpn:
    image: dperson/openvpn-client:latest
    ports:
      - 8112:8112
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${HOME_DIR}/config/vpn:/vpn
    command: '-f "" -r 192.168.1.0/24'
    cap_add:
      - net_admin
    security_opt:
      - label:disable
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.storage == true ]


  deluge:
    image: linuxserver/deluge:latest
    #network_mode: service:vpn
    network: container:vpn
    # --network container:redis 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /storage/torrent:/downloads
      - ${HOME_DIR}/config/deluge:/config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.storage == true ]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.deluge.rule=Host(`deluge.pi-cluster.local`)"
        - "traefik.http.routers.deluge.entrypoints=web"
        - "traefik.http.services.deluge.loadbalancer.server.port=80"
        - "traefik.http.routers.deluge.service=deluge"


#  samba:
#    image: dperson/samba
#    environment:
#      - TZ=${TZ}
#    ports:
#      - "137:137/udp"
#      - "138:138/udp"
#      - "139:139/tcp"
#      - "445:445/tcp"
#    volumes:
#      - /storage:/storage:z
#    command: '-s "storage;/storage;yes;no" -u "media;media" -p'
#    read_only: true
#    tmpfs:
#      - /tmp
#    stdin_open: true
#    tty: true
#    network_mode: host

#  jackett:
#    image: linuxserver/jackett:latest
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /storage/torrent/blackhole:/downloads
#      - ${HOME_DIR}/config/jackett:/config
#    network_mode: host

#  sonarr:
#    image: linuxserver/sonarr:preview
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ${HOME_DIR}/config/sonarr:/config # config files
#      - /storage/tv_shows:/tv
#      - /storage/torrent:/downloads
#    network_mode: host

#  bazarr:
#    image: linuxserver/bazarr
#    ports:
#      - 6767:6767
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ${HOME_DIR}/config/bazarr:/config
#      - /storage/movies:/movies
#      - /storage/tv_shows:/tv
#    network_mode: host

networks:
  public:
    external: true
