version: "3.8"

services:
  deluge:
    image: binhex/arch-delugevpn
    cap_add:
      - NET_ADMIN  # Required to modify networking, like setting up the VPN
    networks:
      - public
    ports:
      - "8112:8112"  # Deluge WebUI
      - "58846:58846"  # Deluge daemon
      - "58946:58946"  # Deluge torrent port
      - "8118:8118"  # Privoxy
    volumes:
      - ./config/deluge:/config
      - /storage/torrent:/data
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.storage == true ]
      restart_policy:
        condition: on-failure
    #healthcheck:
    #  test: curl --fail http://localhost:8112 || exit 1
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    environment:
      VPN_ENABLED: yes
      VPN_PROV: custom
      VPN_CLIENT: openvpn
      # VPN_OPTIONS:
      # VPN_USER: ${VPN_USER}
      # VPN_PASS: ${VPN_PASS}
      STRICT_PORT_FORWARD: yes
      ENABLE_PRIVOXY: yes
      LAN_NETWORK: 192.168.1.0/24
      NAME_SERVERS: 8.8.8.8,8.8.4.4
      DELUGE_WEBUI_PORT: 8112
      #DELUGE_DAEMON_LOG_LEVEL: ${DELUGE_DAEMON_LOG_LEVEL}
      #DELUGE_WEB_LOG_LEVEL: ${DELUGE_WEB_LOG_LEVEL}
      #ADDITIONAL_PORTS: ${ADDITIONAL_PORTS}
      #DEBUG: ${DEBUG}
      UMASK: 002
      PUID: 1000
      PGID: 1000

networks:
  public:
    external: true
